### ISSUE TITLE
Carthage Support?

### ISSUE THREAD

**Issue by Stunner** [nuclearace/SwiftDiscord#47]
Sweet library! Getting set up seems a bit cumbersome. I saw you mentioned disliking CocoaPods. Would you mind adding Carthage support however?

**Comment by nuclearace** [comment]
I'm not sure if it's possible right now. There's a lot of dependencies going on that rely on the SPM.

**Comment by nuclearace** [comment]
Closing since this doesn't feasible in the near term.
