### ISSUE TITLE
How to Authenticate Non-Bot User?

### ISSUE THREAD

**Issue by Stunner** [nuclearace/SwiftDiscord#53]
There is documentation depicting handing the DiscordClient a token (from presumably a bot user). But how would one go about authenticating a regular user account with this library?

**Comment by TellowKrinkle** [comment]
1. Get the token from the local storage of the Discord app ⌥⌘I on Mac, probably something like Ctrl-Alt-I on windows, click the "Application" tab, find the token in Local Storage
2. Use it as the token instead of a bot token (don't prefix with anything)

**Comment by Stunner** [comment]
Thanks man you rock. The shortcut was never working for me so I ended up going to View > Developer > Toggle Developer Tools.
