### ISSUE TITLE
Allow pre iOS 11 Support

### ISSUE THREAD

**Issue by Stunner** [nuclearace/SwiftDiscord#55]
Changing the `Deployment Target` to anything below 11.0 causes the following compiler error to appear:
```
DiscordTableViewController.swift:9:8: Module file's minimum deployment target is ios11.0 v11.0: /Users/aaron/Library/Developer/Xcode/DerivedData/Raidar-fofqjrzpoagmhmegdhcbtcxdfcto/Build/Products/Debug-iphonesimulator/SwiftDiscord.framework/Modules/SwiftDiscord.swiftmodule/x86_64.swiftmodule
```

<img width="472" alt="screen shot 2017-09-23 at 3 04 03 am" src="https://user-images.githubusercontent.com/1133897/30772216-f70e1c12-a00b-11e7-9317-2d3db2c3d2f0.png">

I would like my app to be able to run for devices running iOS 10 (9 ideally) at the very least, until iOS 11 has more adoption.

**Comment by nuclearace** [comment]
Not sure there's much this library can do for that. The SPM doesn't actually support iOS natively.

**Comment by TellowKrinkle** [comment]
Can you go into the SwiftDiscord project and also change its deployment target?

**Comment by Stunner** [comment]
So the SwiftDiscord target doesn't display iOS versions, it displays OS X versions and only goes as far back as 10.6. Manually typing in 10.3 doesn't work either: same compilation error.

<img width="418" alt="screen shot 2017-09-23 at 12 00 52 pm" src="https://user-images.githubusercontent.com/1133897/30776599-60fa6cdc-a05e-11e7-8e59-a8bc67916986.png">

Would compiling this library on Xcode 8 be a viable workaround?

**Comment by TellowKrinkle** [comment]
Does going to Build Settings → <Search Deployment Target> → iOS Deployment Target work?

**Comment by Stunner** [comment]
Oh good call! Turns out I needed to change the deployment target of:

- `SwiftDiscord`
- `StarScream`
- `WebSockets`
- `Crypto`
- `HTTP`
- `Random`
- `TLS`
- `Sockets`
- `URI`
- `Transport`
- `Core`
- `Debugging`
- `Bits`
- `libc`
- `CHTTP`
- `DiscordOpus`

and my iOS target and I got it working. It works as far as iOS 9.0. Do we want to include this in the docs perhaps?

**Comment by TellowKrinkle** [comment]
I think you can do it all at once by setting the setting on the Project rather than a single target.

**Comment by Stunner** [comment]
Yup, you are correct. Thanks!
